// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: guest.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuestJoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Guest  *Guest `protobuf:"bytes,2,opt,name=guest,proto3" json:"guest,omitempty"`
}

func (x *GuestJoinRequest) Reset() {
	*x = GuestJoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestJoinRequest) ProtoMessage() {}

func (x *GuestJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestJoinRequest.ProtoReflect.Descriptor instead.
func (*GuestJoinRequest) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{0}
}

func (x *GuestJoinRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GuestJoinRequest) GetGuest() *Guest {
	if x != nil {
		return x.Guest
	}
	return nil
}

type GuestRequestCancelled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId  string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	GuestId string `protobuf:"bytes,2,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
}

func (x *GuestRequestCancelled) Reset() {
	*x = GuestRequestCancelled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestRequestCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestRequestCancelled) ProtoMessage() {}

func (x *GuestRequestCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestRequestCancelled.ProtoReflect.Descriptor instead.
func (*GuestRequestCancelled) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{1}
}

func (x *GuestRequestCancelled) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GuestRequestCancelled) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

type GuestJoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guest *Guest `protobuf:"bytes,1,opt,name=guest,proto3" json:"guest,omitempty"`
	// Types that are assignable to Answer:
	//
	//	*GuestJoinResponse_JoinApproved
	//	*GuestJoinResponse_JoinDenied
	Answer isGuestJoinResponse_Answer `protobuf_oneof:"answer"`
}

func (x *GuestJoinResponse) Reset() {
	*x = GuestJoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestJoinResponse) ProtoMessage() {}

func (x *GuestJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestJoinResponse.ProtoReflect.Descriptor instead.
func (*GuestJoinResponse) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{2}
}

func (x *GuestJoinResponse) GetGuest() *Guest {
	if x != nil {
		return x.Guest
	}
	return nil
}

func (m *GuestJoinResponse) GetAnswer() isGuestJoinResponse_Answer {
	if m != nil {
		return m.Answer
	}
	return nil
}

func (x *GuestJoinResponse) GetJoinApproved() *JoinApproved {
	if x, ok := x.GetAnswer().(*GuestJoinResponse_JoinApproved); ok {
		return x.JoinApproved
	}
	return nil
}

func (x *GuestJoinResponse) GetJoinDenied() *JoinDenied {
	if x, ok := x.GetAnswer().(*GuestJoinResponse_JoinDenied); ok {
		return x.JoinDenied
	}
	return nil
}

type isGuestJoinResponse_Answer interface {
	isGuestJoinResponse_Answer()
}

type GuestJoinResponse_JoinApproved struct {
	JoinApproved *JoinApproved `protobuf:"bytes,2,opt,name=join_approved,json=joinApproved,proto3,oneof"`
}

type GuestJoinResponse_JoinDenied struct {
	JoinDenied *JoinDenied `protobuf:"bytes,3,opt,name=join_denied,json=joinDenied,proto3,oneof"`
}

func (*GuestJoinResponse_JoinApproved) isGuestJoinResponse_Answer() {}

func (*GuestJoinResponse_JoinDenied) isGuestJoinResponse_Answer() {}

type JoinApproved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *JoinApproved) Reset() {
	*x = JoinApproved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guest_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinApproved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinApproved) ProtoMessage() {}

func (x *JoinApproved) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinApproved.ProtoReflect.Descriptor instead.
func (*JoinApproved) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{3}
}

func (x *JoinApproved) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type JoinDenied struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinDenied) Reset() {
	*x = JoinDenied{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guest_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinDenied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinDenied) ProtoMessage() {}

func (x *JoinDenied) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinDenied.ProtoReflect.Descriptor instead.
func (*JoinDenied) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{4}
}

type Guest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NodeId string `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (x *Guest) Reset() {
	*x = Guest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guest_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guest) ProtoMessage() {}

func (x *Guest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guest.ProtoReflect.Descriptor instead.
func (*Guest) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{5}
}

func (x *Guest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Guest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Guest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_guest_proto protoreflect.FileDescriptor

var file_guest_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0x4e, 0x0a, 0x10, 0x47, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x05, 0x67, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x67, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x15, 0x47, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x22, 0xb0, 0x01, 0x0a, 0x11, 0x47, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x67, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x05, 0x67, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0d, 0x6a, 0x6f, 0x69,
	0x6e, 0x5f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x41, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x6a, 0x6f, 0x69, 0x6e, 0x41, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x64, 0x65, 0x6e,
	0x69, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x6a,
	0x6f, 0x69, 0x6e, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x22, 0x31, 0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x0c, 0x0a, 0x0a, 0x4a, 0x6f, 0x69, 0x6e, 0x44, 0x65,
	0x6e, 0x69, 0x65, 0x64, 0x22, 0x44, 0x0a, 0x05, 0x47, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x42, 0x68, 0x0a, 0x08, 0x63, 0x6f,
	0x6d, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x0a, 0x47, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x63, 0x65, 0x72, 0x6f, 0x68, 0x65, 0x72, 0x6e, 0x61, 0x6e, 0x2f, 0x6d, 0x65, 0x65,
	0x74, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x04, 0x43,
	0x6f, 0x72, 0x65, 0xca, 0x02, 0x04, 0x43, 0x6f, 0x72, 0x65, 0xe2, 0x02, 0x10, 0x43, 0x6f, 0x72,
	0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x04,
	0x43, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_guest_proto_rawDescOnce sync.Once
	file_guest_proto_rawDescData = file_guest_proto_rawDesc
)

func file_guest_proto_rawDescGZIP() []byte {
	file_guest_proto_rawDescOnce.Do(func() {
		file_guest_proto_rawDescData = protoimpl.X.CompressGZIP(file_guest_proto_rawDescData)
	})
	return file_guest_proto_rawDescData
}

var file_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_guest_proto_goTypes = []interface{}{
	(*GuestJoinRequest)(nil),      // 0: core.GuestJoinRequest
	(*GuestRequestCancelled)(nil), // 1: core.GuestRequestCancelled
	(*GuestJoinResponse)(nil),     // 2: core.GuestJoinResponse
	(*JoinApproved)(nil),          // 3: core.JoinApproved
	(*JoinDenied)(nil),            // 4: core.JoinDenied
	(*Guest)(nil),                 // 5: core.Guest
}
var file_guest_proto_depIdxs = []int32{
	5, // 0: core.GuestJoinRequest.guest:type_name -> core.Guest
	5, // 1: core.GuestJoinResponse.guest:type_name -> core.Guest
	3, // 2: core.GuestJoinResponse.join_approved:type_name -> core.JoinApproved
	4, // 3: core.GuestJoinResponse.join_denied:type_name -> core.JoinDenied
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_guest_proto_init() }
func file_guest_proto_init() {
	if File_guest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_guest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestJoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestRequestCancelled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestJoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guest_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinApproved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guest_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinDenied); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guest_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_guest_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*GuestJoinResponse_JoinApproved)(nil),
		(*GuestJoinResponse_JoinDenied)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_guest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guest_proto_goTypes,
		DependencyIndexes: file_guest_proto_depIdxs,
		MessageInfos:      file_guest_proto_msgTypes,
	}.Build()
	File_guest_proto = out.File
	file_guest_proto_rawDesc = nil
	file_guest_proto_goTypes = nil
	file_guest_proto_depIdxs = nil
}
