port: 3001
router:
  region: us-east-1
logger:
  level: debug
jwt:
  issuer: issuer
  secret: secret
redis:
  address: redis.host:6379
  use_tls: false
  db: 0
  username: myuser
  password: mypassword