// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/acerohernan/meet/pkg/config"
	"github.com/acerohernan/meet/pkg/service/auth"
)

// Injectors from wire.go:

func InitializeServer(conf *config.Config) (*Server, error) {
	authService := auth.NewAuthService(conf)
	authMiddleware := auth.NewAuthMiddleware(authService)
	roomService := NewRoomService()
	server := NewServer(conf, authMiddleware, roomService)
	return server, nil
}
